# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newsportal?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wbh53100
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always

# Logger Config
logging:
  level:
    org.bohan.newsportal: debug
